spring:
  datasource:
    url: jdbc:mysql://localhost:3306/triple?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gjsxj455!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath*:schema/schema.sql

# generate-ddl : ddl-auto 를 사용할지 말지 결정, 기본은 true