spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: classpath*:schema/schema.sql
    initialization-mode: always
  jpa:
    generate-ddl: true
